#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

if (process.argv.length != 4){
  console.log('usage: udmt <source> <target>');
  process.exit(1);
}

var template_path = path.join(
  path.resolve(path.dirname(__filename)),
  'template'
);

var template = fs.readFileSync(template_path, 'utf8');

var source_path = process.argv[2];
var target_path = process.argv[3];

var source = fs.readFileSync(source_path, 'utf8');
var template = fs.readFileSync(template_path, 'utf8');

var render = function render(template, values){
  var t = template; 
  template.match(/<%.*?%>/g).forEach(function(m){
    var v = m.replace(/<%\s*(\w+)\s*%>/, '$1');
    t = t.replace(m, values[v]);
  });
  return t;
};

var target = render(template, {target: source});
fs.writeFileSync(target_path, target, 'utf8');
